### ISSUE TITLE
As a user clicking "back" on login page (after a setup), my account should not get messed up PASSBOLT-1589

### ISSUE THREAD

**Issue by mr-gosh** [passbolt/passbolt_browser_extension#1]
i created a demo account and during first login i got an "password not valid" screen

i than went back through to setup process again and messed everything by that i think.
i wasn't able to get logged in... :(

`Your account doesn't exist on server. Contact your admin.`

**Comment by kevinmuller** [comment]
Hi @mr-gosh,
I have checked the logs on the server, and instead it shows that you tried to use a setup token that was already used. This is why you got an error on the second time.
If I understand correctly, you completed a setup first, and then were unable to log in. And then the second time you tried to use the same link again (the one received in your registration email) and you got an error. 
If yes, the error you got after clicking on the link is normal, since the link is only valid for one use. And I would tend to think that you made a typo in your password during your first setup, which would explain why you were getting the "password not valid" error message. This doesn't look like a bug.
Can you try to register again with another email address, complete the setup and log in again ? If you don't have an alternate email address, you can create a temporary one on a service like mailinator (https://mailinator.com/).
Keep us posted!

**Comment by stripthis** [comment]
*Dev notes*

How to reproduce:
- Register and perform setup normally
- Click on the back button of the browser (two times)
- Proceed with another setup procedure
- The login page will say that the user does not exist (the second key is used since unlike other variables it's stored in the keyring disregard of registration status from server API)

What can be done:
- When clicking back from login to setup, display an error message that this is not allowed
- Do not stored the private key in keychain until stored on server side (TBD)
- Allow a user to delete an account that have never logged in using email confirmation (TBD)

**Comment by stripthis** [comment]
ref. PASSBOLT-1589

**Comment by mr-gosh** [comment]
i think the main problem ist that i didn't need to enter the password a second time - and i am not able to reset my account data to the allready regeistered mailadress.

But the reproductionsteps from @stripthis are right - that is how it "happend"...
I'll test it later again...

**Comment by stripthis** [comment]
@mr-gosh the demo was resetted last night so you can even use the same email again. Thanks for trying out passbolt!

**Comment by stripthis** [comment]
Closing as stale. Feel free to reopen if you encounter this, with ideally some information to reproduce the issue.
