### ISSUE TITLE
Plugin not recognized by browsers with API v2.x

### ISSUE THREAD

**Issue by IvanLemos5000** [passbolt/passbolt_browser_extension#138]
## Plugin not recognized by browsers
* Passbolt Version: 3.4.0.
* Platform and Target:
-- Browser: Firefox 95.0.1 and Google Chrome 96.0.4664.110
-- Web server: Ubuntu Server 20.04.3 LTS (GNU/Linux 5.4.0-1030-aws) / Passbolt:2.13.5
-- OS Client: Kubuntu 20.04 Kernel 5.11.0

### What you did
Since the plugin update, on 12/21/21, any browser no longer recognizes and I am unable to login.
I only got one error on Firefox console:
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:40:65

**Comment by cedricalfonsi** [comment]
Hello there,

The browser extension has been released on 3rd December, it might be unrelated to the extension release.

1. Can you confirm that passbolt requests your email when trying to reach your passbolt instance url? You should see the following string:

![image](https://user-images.githubusercontent.com/1582917/147102658-7ccf24f9-5cae-47f5-9d43-845f4132e1b6.png)

2. Can you check the extension console and network.

_On Chrome_: 
New tab > go to chrome://extensions > look for passbolt card > details > inspect views section > click index.html

_On Firefox_:
New tab > go to about:debugging#/runtime/this-firefox > look for passbolt card > Click inspect

3. Can you confirm you didn't change the passbolt url?

4. Can you copy/paste here the result of the server healtcheck?
As root you can execute the following command: `su -s /bin/bash -c "/usr/share/php/passbolt/bin/cake passbolt healthcheck" www-data`

**Comment by IvanLemos5000** [comment]
Hello,
1 - 
When I try to reach my passbolt URL, only shows the 'Download the plugin to get started!' page.
2 -
I attached the console log from Firefox
[console-export-2021-12-22_12-18-30.txt](https://github.com/passbolt/passbolt_browser_extension/files/7763488/console-export-2021-12-22_12-18-30.txt)
3 -
No changes to the URL from server.
4 -
Server log:
[server_log.txt](https://github.com/passbolt/passbolt_browser_extension/files/7763557/server_log.txt)

**Comment by cedricalfonsi** [comment]
Note that if you are installing the browser extension on a new browser and you are running the v2.x, it's an expected behavior. The home page of the application has evolved and the new home page guides the users when they are not identified, which might be your case here.

If you are in this scenario, you have 2 options:
* You can go to http(s)://PASSBOLT_URL/users/recover and request a recovery token. You will then receive an email with a link to follow to initiate your account recovery.
* You can update your API to the latest version. Checkout the online documentation is complete, it will guide you step by step https://help.passbolt.com/hosting/upgrade

If you are not installing the browser extension on a new browser, there are many errors in the healthcheck that need to be tackled. The GPG section looks in a poor state. You can follow the tips and try to sort it out. Also here again, migrating to the Ubuntu package will help you straighten up your configuration.

**Comment by IvanLemos5000** [comment]
Thanks for your support, worked here with the /user/recover, and I'll update my server to the latest API.
