### ISSUE TITLE
Auto-fill / Auto-save / Quick Access feature

### ISSUE THREAD

**Issue by Mte90** [passbolt/passbolt_browser_extension#15]
I am trying to understand what do the extension, I think that is required only to use the service but don't do the most useful thing, the autofill.
I use https://github.com/pfn/passifox that have it so my question is: it is possible to implement it?

Maybe the ideal way is to ask to the server the list of domains and only when the browser go in that website ask for the password to prefill the values.

**Comment by stripthis** [comment]
Hi @Mte90, thanks for dropping by :)

The plugin currently is needed to maintain a higher level of security: to ensure the integrity of the cryptographic code, provide a secure random number generator, make sure sensitive data like the master password are not accessible by javascript running on a page (since plugin and page js code are not in the same sandbox). 

The autofill is on our roadmap we started working on some early early specifications, since most of our users are indeed asking how it will look like (sneak peek: https://docs.google.com/document/d/1BFkFa4x32ASPPv6oKrQNOA9dzhg557AgBuj-t9iekIs/edit?usp=sharing ). Our current focus is the group feature, but we'll work on the autofill at some point in the coming months.

**Comment by stripthis** [comment]
@kevinmuller some interesting technical approach here: https://arxiv.org/abs/1706.05085

> Instead of exposing actual credentials to the DOM, a dummy username and password are autofilled by the untrusted component. The trusted component intercepts and modifies POST requests before they are encrypted and sent over the network. Our approach only works for websites that do not manipulate entered credentials in the browser client.

**Comment by teamfighter** [comment]
Any updates here?

**Comment by stripthis** [comment]
@teamfighter this feature is scheduled to be delivered in winter 2017. No updates apart from that.

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-user-the-passbolt-extension-can-auto-fill-auto-save-my-passwords-in-forms/82
