### ISSUE TITLE
Failed to fetch on Edge Browser!

### ISSUE THREAD

**Issue by shahesam84** [passbolt/passbolt_browser_extension#195]
##IMPORTANT: PLEASE READ

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to an installation: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

This is only a issue tracker for bugs related to the Passbolt Browser Extensions.
For passbolt API, docker, command line interface, in short any other bugs 
please use [the other relevant repositories](https://github.com/passbolt).

If you are certain this is a new Browser Extension bug please use the following format:

## Edge browser extension throws failed to fetch as login screen after updating to CE 4.2.0
* Passbolt Version: CE 4.2.0
* Platform and Target:
-- Browser: Edge Version 117.0.2045.31
-- Web server: nginx/1.18.0 (Ubuntu)
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
The Passbolt CE server to version 4.2.0.

### What happened
Users may occasionally encounter a "failed to fetch" error message when attempting to log into their account using the Passbolt Edge extension.

### What you expected to happen
The normal login screen to be shown instead of the error message.
![MicrosoftTeams-image (7)](https://github.com/passbolt/passbolt_browser_extension/assets/28066480/e06861c5-21f5-433f-b2ef-ae36a13e8e3a)

**Comment by Benj1er** [comment]
Hello @shahesam84,

I'm sorry to read that you are encountering an issue.
Thanks for your report.

Does this behavior reoccur when the user tries to log in to their account again using the Passbolt Edge extension?

In order to help you I would need some additional information:
Your browser's console trace, in edge:
- go to edge://extensions/
- Enable developer mode
- Click on the index.html link in the inspect views section of the Passbolt extension tail
- When you encounter the issue, copy/paste what you see in the console tab

A follow-up ticket was created on the internal tracker: PB-27783


Best regards

**Comment by shahesam84** [comment]
Yes, this happens when a user tries to log in to an account. I will provide you with the requested information once the error occurs next time.

**Comment by shahesam84** [comment]
Here's what you requested from DevTools Console.
![image](https://github.com/passbolt/passbolt_browser_extension/assets/28066480/7270a12c-10a7-4d71-bec7-b27ce7632e06)

**Comment by Benj1er** [comment]
Hello @shahesam84,

Sorry for my late reply, this problem is not easy to solve but I have found a few tasks you can try to resolve a certificate error.
Since the Edge browser is a Chromium-based browser, here's a link to solve a certificate problem:
[https://www.wildcardsslcertificate.com/how-to-fix-err-bad-ssl-client-auth-cert-for-google-chrome#:~:text=This%20SSL%20certificate%20error%20mainly,issued%20from%20non%2Dtrustworthy%20sources](https://www.wildcardsslcertificate.com/how-to-fix-err-bad-ssl-client-auth-cert-for-google-chrome#:~:text=This%20SSL%20certificate%20error%20mainly,issued%20from%20non%2Dtrustworthy%20sources)

Please let me know if it did or did not solve your problem.

**Comment by Benj1er** [comment]
Hello @shahesam84 ,

The error message has been updated to be clearer.
As it seems to be related to a configuration problem, I have closed it.
Please feel free to reopen it if the issue persists.

Best regards
