### ISSUE TITLE
Could not retrieve server key. Please contact administrator

### ISSUE THREAD

**Issue by mikemix** [passbolt/passbolt_browser_extension#28]
I just found out about this thread: https://github.com/passbolt/passbolt_browser_extension/issues/12

but I simply don't know which key are we talking about :frowning: can't get through this and setup my admin account.

**Comment by stripthis** [comment]
Hello,

You can get this issue for two reasons:
- you are not using a valid domain name
- the server public key does not contain an email address.

The server key is the one you generate for the server during the installation. It is the one you mention in the app/Config/app.php.

If you are sure you have this problem because of another issue than this two, please reopen the issue.

I hope this helps.

**Comment by mikemix** [comment]
1) I am using a valid domain name which is already added to our dns servers
2) Are we talking about the gpg key? If yes it does contain an email address where it asked about it. I did follow this instructions to install passbolt https://www.svennd.be/installing-passbolt-on-centos-7/

**Comment by mikemix** [comment]
@stripthis thx! I forgot to rerun the setup script. This issue should go to the "Installation" FAQ page.
