### ISSUE TITLE
Chrome Extension in version 1.6.10 - permission to manage downloads

### ISSUE THREAD

**Issue by rafal-kos** [passbolt/passbolt_browser_extension#43]
Hello,

Any idea why version 1.6.10 require permission to manage downloads in Chrome? I don't see any track of that in the CHANGELOG.

Thanks in advance,

**Comment by stripthis** [comment]
The previous system which we used to download private and public keys stopped working. It seems that the Chrome developer wants us to use the dedicated API. It also offers more option for the user to choose where to safe the files instead of dumping everything in default download directory.

See. https://community.passbolt.com/t/chrome-private-key-download/420/8

**Comment by stripthis** [comment]
Changelog was not updated on master, it's fixed.
