### ISSUE TITLE
Login: Username cannot be edited

### ISSUE THREAD

**Issue by joachimneumann** [passbolt/passbolt_browser_extension#57]
## ISSUE NAME
* Passbolt Version: I don't know which version I am using. As of March 10, 2019, the commit hash for the browser extension was b6f5e62
* Platform and Target:
Chrome 72.0 and 65.0 on MacOX 10.14.3

### What you did
I created a demo account with the admin user joachim@mindo.io: https://demo.passbolt.com/mindo-software-slu. Then I created a secondary user joachim@joachimneumann.com to test password sharing. After logging in and out as joachim@joachimneumann.com I was unable to login again as joachim@mindo.io, because the Username field is not editable, see the attached screenshot.

<img width="1146" alt="username not editable" src="https://user-images.githubusercontent.com/5642225/54081316-48fcca00-4303-11e9-8a15-e279f38ed859.png">

I would expect the username to be editable. I had to execute an account recovery in order to be able to login again as the Passbolt admin user joachim@mindo.io

In the Chrome developer tools I could see that the input field was disabled, but I don't understand why this happened:
`<input name="data[User][username]" class="required fluid" maxlength="50" type="text" id="UserUsername" required="required" value="" disabled="disabled">`

**Comment by stripthis** [comment]
Hello,

The username cannot be edited because it is linked with the configuration in the plugin (e.g. domain name / username / user key associations). We plan to support multi account this year so that a recover is not needed to switch accounts.

Please make feature request / enhancement on the community forum: https://community.passbolt.com/
This helps keeping the discussion in one place / avoiding double entries.
