### ISSUE TITLE
I should be able to reset extension

### ISSUE THREAD

**Issue by bestlibre** [passbolt/passbolt_browser_extension#7]
Is it possible to reset the extension parameters ? I would like to start over with a new user. Another use case would be to use passbolt from a shared computer with multiple users.

Thanks

**Comment by kevinmuller** [comment]
Hi,

The extension parameters will reset by themselves if you create a new user and go through the extension setup once again (by clicking on the activation link that you receive by email).

Multi-accounts is a feature that is already in our roadmap, but is currently not a high priority.

Cheers,
Kevin

**Comment by bestlibre** [comment]
I already have setup this user on another computer. On my work computer I have performed some test but would like to use my real user.
I have tried to remove the extension, restart firefox and reinstall it but the previous (test) user was still present. Is there a file somewhere I can edit to workaround that ? Since I cannot create a new user and setup it on two computer (or can I ?), I don't know how to have the same user on my two computers.

**Comment by kevinmuller** [comment]
Did you try to do a recover procedure for your "real" user on your work computer ? (or maybe you faced [the bug you already reported](https://github.com/passbolt/passbolt_api/issues/33) ? Or you didn't find the link to the recover ?)

It is possible to have the same user on multiple computers with a recover (but maybe it is not possible in your case because of the bug #33)

Additionally to what I said earlier, multiple users on one computer is actually possible with the browser built-in "people" functionality (chrome). I will edit my first answer to reflect this.

**Comment by bestlibre** [comment]
I face the bug #33, but I was also not able to recover because I already have a "test" user configured. I found a solution for this last problem : by deleting the file "jetpack/passbolt@passbolt.com/simple-storage/store.json" in the firefox profile folder I was able to reset the extension.

**Comment by kevinmuller** [comment]
Glad to see that the problem is solved!

Happy password management ;)
Cheers.

**Comment by bestlibre** [comment]
I haven't found the procedure to change the passphrase in the doc. Perhaps it could be added somewhere ?

- export private key
- import in gpg
- edit key and change passphrase
- recover account with edited key

**Comment by stripthis** [comment]
@bestlibre we added the workaround to the change the passphrase to the FAQ. Thanks,
