### ISSUE TITLE
Blocking error - Could not verify server key. Failed to fetch. Possible Letsencrypt ssl certificate related 

### ISSUE THREAD

**Issue by qunabu** [passbolt/passbolt_browser_extension#73]
Hello.
First of all thanks for such a great community software.

I’ve been using passbolt for a couple for months with my team without any issue, yet it had stop recenlty working with giving errors “Could not verify server key. Failed to fetch” on chrome and “Could not verify server key. NetworkError when attempting to fetch resource.” on Firefox.

My environment hasn’t changed a bit during the time error occurs. I’ve updated passbolt to latest but error remains.

running heatlhcheck on the servers returns " No error found. Nice one sparky!" turning debug mode doesnt gives any revelant info as well.

I’ve been diggin for last two days to see what happen and the only thing that had changed is a new Lets Encrypt ssl certificate that was installed automatically by certbot and since then the browser cannot work. 

What else could be done to fix this error ?

**Comment by cedricalfonsi** [comment]
Hello @qunabu,

I'm sorry to read that you are encountering an issue.
Your client is not able to reach your API, it's probably not a passbolt problem, but let see if we can help you.

In order to help you I would need some additional information :
* Passbolt Version: EXACT RELEASE VERSION OR COMMIT HASH
* Browser environment : NAME AND VERSION
* Your Passbolt errors log: PASSBOLT_PATH/logs/error.log
* Your Nginx errors log
* Your browser console trace, in chrome :
- go to `chrome://extensions/`
- Enable developer mode
- Click on the `index.html` link in the inspect views section of the Passbolt extension tail
- Reload your page, and copy/paste what you see in the console tab

**Comment by qunabu** [comment]
Those steps 

- go to chrome://extensions/
- Enable developer mode
- Click on the index.html link in the inspect views section of the Passbolt extension tail
- Reload your page, and copy/paste what you see in the console tab

Give me exact information of what was wrong. Thank you so much and have a great day
