### ISSUE TITLE
CSRF token mismatch.

### ISSUE THREAD

**Issue by fthzkrtn** [passbolt/passbolt_browser_extension#82]
I build the extension and installed it manually into the chrome. Everything works fine except creating something new. I could not create any password or user. It says me that "CSRF token mismatch". When I'm looking into request headers see something like:
```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,tr;q=0.8
Connection: keep-alive
Content-Length: 743
Content-Type: application/json
Cookie: csrfToken=************; CAKEPHP=********
DNT: 1
Host: local.passbolt.com
Origin: https://local.passbolt.com
Referer: https://local.passbolt.com/app/passwords
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
X-CSRF-Token: null
X-Requested-With: XMLHttpRequest
```
I'm using Passbolt behind reverse proxy with multiple virtual hosts and trying to solve this issue about 2 working days. Really need your help.

## ISSUE NAME
* Passbolt Version: Docker Container hosted on Ducker Hub
* Platform and Target:
-- Browser: Chrome 72.0.3626.119
-- Web server: Nginx 1.14.0 / Ubuntu
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
Followed these instructions to use passbolt https://help.passbolt.com/hosting/install/ce/docker.html

And Followed these instructions to build passbolt-extension https://github.com/passbolt/passbolt_browser_extension

Here is my Nginx conf:
```
upstream passbolt{
  server 127.0.0.1:4343;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name local.passbolt;
  add_header X-XSS-Protection "1; mode=block";
  proxy_cookie_path / "/; HTTPOnly; Secure";

  ssl on;
  ssl_certificate /etc/nginx/certs/ssl/cert.crt;
  ssl_certificate_key /etc/nginx/certs/ssl/cert.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

  ssl_prefer_server_ciphers   on;
  ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA HIGH !RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS";
  ssl_dhparam    /etc/nginx/certs/dhparams.pem;

  location / {
    proxy_pass https://passbolt/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forward-Proto http;
    proxy_set_header X-Nginx-Proxy true;
    proxy_redirect off;
  }
}
```
### What happened
After creating user and logging into the passbolt tried to create a secure password and it gives me CSRF token mismatch error with code 403. And could not see any detailed log in "docker logs" or nginx reverse proxy logs.

**Comment by stripthis** [comment]
Hello,

To prevent Cross Site Request Forgery or CSRF attacks a CSRF token must be included in all future requests that affects the integrity of the data (e.g. a resource edit or a user delete action for example). This makes sure that an attaquer can not create a malicious website that would trigger an action in passbolt, e.g prevent “clickjacking”.

You can access this CSRF when accessing any read endpoint using the cookie csrfToken. In addition to request data parameters, CSRF tokens can be submitted through a special X-CSRF-Token header. Using a header often makes it easier to integrate a CSRF token with applications consuming the API.

So i'm assuming on your setup the CSRF token cannot be transmitted maybe because you are suppressing the header on nginx side?
