### ISSUE TITLE
Unable to create password / share with API server v2.1

### ISSUE THREAD

**Issue by vojtechfidler** [passbolt/passbolt_browser_extension#98]
ISSUE NAME
* Passbolt Version: unknown
* Platform and Target:
-- Browser: Chrome
-- Web server: pwd.revolt.bi

### What you did
I try to retrieve password

### What happened
The whole browser window freezes and I am unable to get the password. 

### What you expected to happen
I expect to have a window opened where I fill key and get the password

**Comment by cedricalfonsi** [comment]
Hello @vojtechfidler,

In order to help you I would need more information.
- Are you trying to access your passwords via the quickaccess (toolbar icon)? Or via the main interface of passbolt?
- What is your chrome version? You should find it in the main chrome menu: About Google Chrome.
- What is the passbolt plugin version? You can get it after you are logged in passbolt, by pointing your mouse on the heart at the bottom right of your screen. If you cannot log because the application is freezing, you can get it here: chrome://extensions/
- What is the version of the passbolt server? If you can login you can retrieve as the previous one with the heart. If not, right after the login, don't wait the interface to load, and point to the following url: http://passbolt.local/settings.json.

**Comment by charlypeluch** [comment]
Same Issue:

- SO: Ubuntu Mate 18.04
- Browser: Chromium 81
- Passbolt Version: -
- Extension Version: 2.13.0

**What you did**
I try to retrieve password

**What happened**
The whole browser window freezes and I am unable to get the password.

**What you expected to happen**
I expect to have a window opened where I fill key and get the password

The error has appeared to me from the update of the extension to the latest version.

**Comment by stripthis** [comment]
@charlypeluch can you answer @cedricalfonsi questions above also?

**Comment by vojtechfidler** [comment]
Hi Cedric,

thank you for your reaction!

1. I am trying to access the password from the main interface.
Interestingly, it is possible to retrieve password from the toolbar (i.e.
plug-in)
2. Version is 83.0.4103.61 but I tried latest version of Firefox and I get
the same error
3. Numbers I am getting is 2.1.0 / 2.13.0
4. Please see above. Dont know which one is plugin and which one is server.

Thanks for support. I have also issues sharing the password.

Vojtech

pá 29. 5. 2020 v 15:13 odesílatel Cedric <notifications@github.com> napsal:

**Comment by charlypeluch** [comment]
@stripthis i update my post, thank.

**Comment by stripthis** [comment]
Can you update your passbolt server version, v2.1 is around two year old (Jun 14, 2018), so there might be some backward compatibility issues.

**Comment by vojtechfidler** [comment]
Thank you, this seems as a potential source of issue. I can't do the update
myself, but I forwarded the feedback to the server admin.

pá 29. 5. 2020 v 16:31 odesílatel Remy <notifications@github.com> napsal:

**Comment by cedricalfonsi** [comment]
I close this ticket as migrating to the latest version solves this issue for others:
See: https://www.passbolt.com/pricing/pro
